"""Add currency field to orders table

Revision ID: 092578dc13cc
Revises: ae9da7341fd6
Create Date: 2025-08-27 22:03:48.765734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092578dc13cc'
down_revision = 'ae9da7341fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('fee_configs', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
