"""Add account_id and submitter to expenses

Revision ID: 4989b8cef25c
Revises: 092578dc13cc
Create Date: 2025-08-29 15:59:27.261211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4989b8cef25c'
down_revision = '092578dc13cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitter', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_expenses_account_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_account_id', type_='foreignkey')
        batch_op.drop_column('submitter')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
