"""Add multi-currency support to expenses

Revision ID: 607865bc8660
Revises: 4989b8cef25c
Create Date: 2025-09-01 02:24:07.186151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607865bc8660'
down_revision = '4989b8cef25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('original_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=6), nullable=True))

    with op.batch_alter_table('recharges', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('original_amount')
        batch_op.drop_column('original_currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recharges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_currency', sa.VARCHAR(length=10), server_default=sa.text("'CNY'"), nullable=True))
        batch_op.add_column(sa.Column('original_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('(1.0)'), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('original_currency')
        batch_op.drop_column('original_amount')

    # ### end Alembic commands ###
