"""Update fee_config model fields

Revision ID: ae9da7341fd6
Revises: 
Create Date: 2025-08-12 13:11:41.149589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9da7341fd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_configs', schema=None) as batch_op:
        # 先添加可为空的新列
        batch_op.add_column(sa.Column('fee_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fee_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calculation_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('percentage_rate', sa.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fixed_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    
    # 更新现有数据的默认值
    connection = op.get_bind()
    connection.execute(sa.text(
        "UPDATE fee_configs SET "
        "fee_type = COALESCE(provider, 'other'), "
        "fee_name = COALESCE(name, '未命名费用'), "
        "calculation_method = CASE WHEN percentage_fee IS NOT NULL AND percentage_fee > 0 THEN 'percentage' ELSE 'fixed' END, "
        "percentage_rate = CASE WHEN percentage_fee IS NOT NULL THEN percentage_fee * 100 ELSE NULL END, "
        "fixed_amount = COALESCE(fixed_fee, 0.00)"
    ))
    
    # 将列设置为非空
    with op.batch_alter_table('fee_configs', schema=None) as batch_op:
        batch_op.alter_column('fee_type', nullable=False)
        batch_op.alter_column('fee_name', nullable=False)
        batch_op.alter_column('calculation_method', nullable=False)
        
        # 删除旧列
        batch_op.drop_column('fixed_fee')
        batch_op.drop_column('provider')
        batch_op.drop_column('name')
        batch_op.drop_column('percentage_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage_fee', sa.DECIMAL(precision=5, scale=4), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('fixed_fee', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('fixed_amount')
        batch_op.drop_column('percentage_rate')
        batch_op.drop_column('calculation_method')
        batch_op.drop_column('description')
        batch_op.drop_column('fee_name')
        batch_op.drop_column('fee_type')

    # ### end Alembic commands ###
